remove comment

diff --git a/benchmarks/run b/benchmarks/run
--- a/benchmarks/run
+++ b/benchmarks/run
@@ -1,34 +1,34 @@
 # #!/bin/bash
 
-# set -e
+set -e
 
-# export frum_DIR
+export frum_DIR
 
-# BASE_DIR="$(dirname "$(realpath "$0")")"
-# cd "$BASE_DIR" || exit 1
+BASE_DIR="$(dirname "$(realpath "$0")")"
+cd "$BASE_DIR" || exit 1
 
-# frum_DIR="$(mktemp -d)"
-# export PATH="$BASE_DIR/../target/release:$PATH"
+frum_DIR="$(mktemp -d)"
+export PATH="$BASE_DIR/../target/release:$PATH"
 
-# mkdir results 2>/dev/null || :
+mkdir results 2>/dev/null || :
 
-# if [ ! -f "$BASE_DIR/../target/release/frum" ]; then
-#   echo "Can't access the release version of frum"
-#   exit 1
-# fi
+if [ ! -f "$BASE_DIR/../target/release/frum" ]; then
+  echo "Can't access the release version of frum"
+  exit 1
+fi
 
-# if ! command -v hyperfine >/dev/null 2>&1; then
-#   echo "Can't access Hyperfine. Are you sure it is installed?"
-#   echo "  if not, visit https://github.com/sharkdp/hyperfine"
-#   exit 1
-# fi
+if ! command -v hyperfine >/dev/null 2>&1; then
+  echo "Can't access Hyperfine. Are you sure it is installed?"
+  echo "  if not, visit https://github.com/sharkdp/hyperfine"
+  exit 1
+fi
 
-# chmod +x ./frum
-# chmod +x ./rbenv
-# chmod +x ~/.frum-latest/frum
+chmod +x ./frum
+chmod +x ./rbenv
+chmod +x ~/.frum-latest/frum
 
-# export PATH="$HOME/.rbenv/bin:$PATH"
-# export PATH="$HOME/.rbenv/shims:$PATH"
+export PATH="$HOME/.rbenv/bin:$PATH"
+export PATH="$HOME/.rbenv/shims:$PATH"
 
 hyperfine \
   --warmup=2 \
